gnustep/libs-back

ChangeLog
Headers/x11/XGGeneric.h
Source/x11/XGServerWindow.m

Map application icon window without focus switch for applications executed with argument `-autolaunch YES` in WindowMaker environment.

Handle `-autolaunch YES` application argument

---

ChangeLog
Source/x11/XGServerEvent.m

Old code sent to WM only single-click. 
Receiving double-click on GNUstep appicons allows WindowMaker to perform its own focus change related actions.

Send double-click on appicon to WindowMaker

---

ChangeLog
Source/x11/XGServer.m
Source/x11/XGServerEvent.m

Double-click time, move threshold, scroll wheel multiplier, menu button configuration: enable/disable, left/right.
Things which are need to be done in GUI:
- NSUserDefaults should send notification to NSDistributedNotificationCenter on defaults change. This will allow all running applications adjust mouse properties on the fly.
- NSScrollView (NSScroller) should respect "GSMouseScrollMultiplier" value.

Support for configurable mouse properties

---

ChangeLog
Source/x11/XGServerWindow.m

Fix for displaying of colored mouse cursor images.
Cleanup in Xlib cursor images loading - do not load cursors which handled by NSCursor.
Complementary to https://github.com/gnustep/libs-gui/pull/30.

Mouse cursor images handling fix and cleanup

---

.gitignore
Headers/fontconfig/FCFaceInfo.h
Source/art/FTFontEnumerator.m
Source/art/ftfont.m
Source/cairo/CairoFontInfo.m
Source/fontconfig/FCFaceInfo.m
Source/fontconfig/FCFontEnumerator.m
Source/fontconfig/FCFontInfo.m

This is a semi-comprehensive revamp of the font system in use with the Cairo backend.
I have implemented support for Fontconfig 2.11's unique PostScript font descriptors, which prevents synthesized font names from causing fonts to "shadow" each other. For people with very old versions of fontconfig, I have added many new rules for synthesizing new font descriptors, which should limit that shadowing effect drastically, as well as made use of each font's human-readable name to improve the user interface (and make shadowing even less likely).
I have also introduced sorting for the font list, which causes the faces within a font to become sorted by weight and traits, so that the user-visible list now has a discernible pattern to it that it lacked before.
I have used Cairo's and Fontconfig's …

Font system revamp

---

ChangeLog
Source/x11/XGServerWindow.m

If application icon placed into WM_HINTS properties of window (at least for WindowMaker) alpha channel in image missed and icon in Dock looks weird. For example look into [issue #227](https://github.com/trunkmaster/nextspace/issues/227) in NextSpace.

Correct application icon images in WM

---

ChangeLog
Source/x11/XGServerEvent.m

This fix primary goal is to manage the following case:
- user opens application on workspace0 with some window (say Terminal);
- user switched to workspace1;
- user activates Terminal by double-clicking on appicon;
- Terminal main menu will be shown, but input focus was left on Terminal window left on workspace0.
Also, I think I've made _handleTakeFocusAtom:forContext: more correct and maintainable due to the usage of window that receives TakeFocus request instead of last window used by application.

TakeFocus request handling fix

---

ChangeLog
Headers/x11/XGServer.h
Headers/x11/XGServerWindow.h
Source/art/ARTContext.m
Source/cairo/XGCairoSurface.m
Source/x11/XGDragView.m
Source/x11/XGServer.m
Source/x11/XGServerEvent.m
Source/x11/XGServerWindow.m
Source/x11/XIMInputServer.m
Source/x11/XWindowBuffer.m

In addition to the previous PR I've made some optiomizations and fixes:
- implemented caching of monitors parameters;
- fixed monitors enumeration - NSScreen receives correct array with indices to monitors parameters cache;
- fixed/unified handling count of monitors/screens with RandR and without it.
- boundsForScreen now should run much faster because of cached parameters use.

Screens handling with RandR fixes

---

ChangeLog
Source/x11/XGServerWindow.m

Transform screen origin into unflipped (OpenStep) coordinate system for XRandR capable systems. After this change windows and screen will use the same start of coordinate system for their origins.

Align screens origin to OpenStep coordinate system.

---

ChangeLog
Source/x11/XGServerWindow.m

Using `window->xframe` for making decisions provides ability to alter NSWindow's _frame variable before `placewindow:for:` call without affecting actual Xlib window placement.

Window positionning: rely on internal variable not the GUI's one

---

ChangeLog
Source/x11/XGServerWindow.m

When monitors layout was changed windows need to update their positions on screen. There are the cases when OpenStep frames is not changed while Xlib did and vise versa. This fix adds checks for OpenStep frame changes as well as Xlib's.

placewindow:: fix frame check for multi-monitor layout 

---

Source/xlib/XGBitmap.m
Source/xlib/XGGeometry.m
Tools/gpbs.m

Taken from the Debian "gnustep-back" package sources, which attribute
these changes to:
Author: Eric Heintzmann <heintzmann.eric@free.fr>
Author: Yavor Doganov <yavor@gnu.org>

Fix a bunch of typos

---

ChangeLog
Source/x11/XGServerEvent.m

If application (window) receives WM_TAKE_FOCUS in hidden state it means WindowMaker wants us to be unhidden.
Description: There are 2 protocols defined in XGServerWindow.h - WMFHideApplication and WMFHideOtherApplications. These protocols exist to help GNUstep application and WindowMaker notify each other about "Hide" and "Hide Others" actions. There are no protocols for "unhide" action.
Test case steps:
1. Open application with window opened.
2. Hide application with "Hide" menu item.
3. Open WindowMaker's "Windows" menu (middle-click on desktop).
4. Select hidden application window.
Application unhides, activates, restored window is focused (receives) input and "Hide" menu item unselected.

XGServerEvent.m: unhide app if WindowMaker sends WM_TAKE_FOCUS to window

---

ChangeLog
Source/x11/XGServerWindow.m

The removed code removed creates and maps zero-sized window in hope that WindowMaker will recognize app by this event and  create app icon window. Although when application requests window for appicon through the `-window::::` method call, it returns newly created and mapped window. This actually happens but application icon flickers between WM icon creation and application icon window appearance.
This fix based on the fact that root application window (ROOT) is mapped in `-orderwindow:::` and this is the event of application recognition by WindowMaker because it is a first application window that is mapped.
I've made tests on WindowMaker and NextSpace Workspace WM with ART and Cairo backends. Applications started with double-click is started with 'highlighted' icon and then normal icon …

x11/XGServerWindow.m: removed WindowMaker appicon hack

---

Headers/cairo/WaylandCairoShmSurface.h
Headers/wayland/WaylandServer.h
Source/cairo/CairoContext.m
Source/cairo/GNUmakefile
Source/cairo/WaylandCairoShmSurface.m
Source/wayland/WaylandServer+Layershell.m
Source/wayland/WaylandServer+Xdgshell.m
Source/wayland/WaylandServer.m

This PR is a refactor of the WaylandCairoSurface, which is an implementation of a Wayland shared memory surface. It includes:
- some documentation on how it works
- a buffer release listener to fix the memory leak present before
- rename to a more specific name as more Wayland surface implementations are possible
- move `wl_surface_attach` calls from the server into the surface class

Wayland shm surface

---

Headers/cairo/WaylandCairoShmSurface.h
Headers/wayland/WaylandServer.h
Source/cairo/CairoContext.m
Source/cairo/GNUmakefile
Source/cairo/WaylandCairoShmSurface.m
Source/wayland/WaylandServer+Cursor.m
Source/wayland/WaylandServer+Keyboard.m
Source/wayland/WaylandServer+Layershell.m
Source/wayland/WaylandServer+Xdgshell.m
Source/wayland/WaylandServer.m
configure
configure.ac

This PR depends on the following PRs:
- https://github.com/gnustep/libs-back/pull/34
- https://github.com/gnustep/libs-gui/pull/124
It is a refactor of the current cursor handling for the wayland backend and it includes:
- warnings cleanup
- new library dependency on `wayland-cursor` to load cursor images from the X theme
- mouse dragging
- window move/resize refactor depends on: https://github.com/gnustep/libs-gui/pull/124
- pointer axis source to distinguish between mouse scroll and touch scroll
- hide/show cursor
- set image cursor
- mapping between gnustep cursor styles and X themes icons

Wayland backend pointer events and cursor images

---

Source/wayland/WaylandServer+Cursor.m

related to https://github.com/gnustep/libs-gui/commit/b84d8cc3fd4eb198b2021ebed2b03fd942802620

wayland: use GSStandardWindowDecorationView to hit-test cursor clicks

---

Source/winlib/WIN32FontInfo.m

I've seen `[Win32FontInfo setupAttributes]` being called when `familyName` is `nil`, which will cause a call to `wcsncpy` with the second argument being `NULL`, resulting in an AV.
This PR works around that.  In this implementation, when familyName` is `nil`:
- `logfont.lfFaceName` will not be set
-  `CreateFontIndirectW` will fail 
- [Win32FontInfo setupAttributes] will now return `NO` instead of failing with an AV

Avoid AV in Win32FontInfo setupAttributes

---

Source/wayland/WaylandServer+Cursor.m
Source/wayland/WaylandServer+Keyboard.m
Source/wayland/WaylandServer+Xdgshell.m
Source/wayland/WaylandServer.m

This pull request resolves several build errors encountered when compiling with Wayland support (./configure --enable-server=wayland) on Debian 13 Testing (codename trixie) using Clang version 16.0.6.
The updates include:
- Selector Naming Issues: Corrected method declarations to properly align with Objective-C selector conventions.
- Function Pointer Compatibility: Fixed mismatched function pointer types to align with expected signatures.
- Implicit Declarations: Added necessary includes and declarations for Wayland functions to prevent implicit declaration errors.
- Type Corrections: Adjusted type usage to match expected formats and avoid type mismatch errors.
If this PR is accepted, I will work on a follow-up PR will address additional build issues on Arch Linux with Clang 18.1.8.

Fix build errors with Wayland on Debian 13 (trixie) using Clang 16

---

Tools/gpbs.m

When building for Windows using a native toolchain (i.e. not MinGW or MSYS), `<unistd.h>` is not available.  Include `<io.h>` instead and define `strcasecmp`.

Support building natively on Windows

---

Source/win32/WIN32Server.m
Source/win32/w32_windowdisplay.m
Tools/win32pbs.m

The Windows SDK declares `BOOL` as an `int`.  Objective C defines `BOOL` as a `char`. Those two types clash.  MinGW's implementation of the Windows SDK uses the `WINBOOL` type to avoid this clash.  When compiling natively on Windows, we need to manually define `WINBOOL`.
MinGW will define `_DEF_WINBOOL_` if it has defined `WINBOOL` so we can use the same trick here.
See https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-headers/include/ntdef.h#L355

Define WINBOOL on non-MinGW platforms

---

Source/x11/XIMInputServer.m

Issue described in https://github.com/gnustep/libs-back/issues/49
I found out that sometimes XLookupString returns more than one char for a single key, which does not make much sense for Latin1.
So I suspect I am getting back UTF-8 in that case and indeed, interpreting that string as such works!
Looks like X11 got "extended" here beyond the Spec that says Latin1 only. The question remains why it is happening for characters contained in Latin1?
Last found is that €, not contained in Latin1 gets not back.
However I think this "hack" is pretty safe, since if only one char is returned, Latin1 is used as per-spec.

try to fix extended char handling in NSEvent
